name             'mutt'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mutt'
long_description 'Installs/Configures mutt'
version          '0.1.0'
